---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: "chore"
    target-branch: main
    reviewers:
      - "EasyDynamics/oscal-editor-reviewers"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: "chore"
    target-branch: next
    reviewers:
      - "EasyDynamics/oscal-editor-reviewers"
