---
changelog:
  exclude:
    labels:
      - chore
      - dependencies
    authors:
      - dependabot[bot]
  categories:
    - title: Fixed Bugs
      labels:
        - bug
    - title: New Features
      labels:
        - enchancement
