---
changelog:
  exclude:
    labels:
      - chore
      - dependencies
    authors:
  categories:
    - title: New Features
      labels:
        - enchancement
    - title: Bug fixes
      labels:
        - bug
