---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Update NPM"
      - npm install -g npm lerna
      - echo "Installing library npm packages"
      - npm ci
  build:
    commands:
      - echo "Build all packages"
      - lerna run build
      - echo "Testing library"
      - lerna run test --scope="@easydynamics/oscal-react-library"

artifacts:
  base-directory: ./packages/oscal-viewer/build
  files:
    - '**/*'
  exclude-paths:
    - 'robots.txt'

cache:
  paths:
    - './node_modules/**/*'
    - './packages/**/node_modules/**/*'
