version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing npm packages
      - npm install
  build:
    commands:
      - echo "Build library"
      - npm run build
      - echo "Testing library"
      - npm run test -- --ci --watchAll=false
      - echo "Testing sample application"
      - cd example
      - npm run test -- --ci --watchAll=false
      - cd ..
      - echo "Building sample application"
      - npm run predeploy

artifacts:
  base-directory: ./example/build
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'
    - './example/node_modules/**/*'
