version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing npm packages
      - npm install
  build:
    commands:
      - echo Building
      - npm run build
      - echo Testing
      - npm run test -- --ci --watchAll=false

artifacts:
  base-directory: ./build
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'