name: Adds all issues to the project board

on:
  issues:
    types:
      - opened

env:
  PROJECT_ORG: "EasyDynamics"
  PROJECT_ID: "2"

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Login as the automation app
        # This Action generates a token from the GitHub App and provides it as
        # an output. It _does_ register that token as a secret so that it will be
        # filtered from log output automatically
        id: generate-token
        # This maps to v1.6.0 https://github.com/tibdex/github-app-token/releases/tag/v1.6.0
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/${{ env.PROJECT_ORG }}/projects/${{ env.PROJECT_ID }}
          github-token: ${{ steps.generate-token.outputs.token }}
