name: Publish to GitHub Packages
on:
  push:
    branches: [EGRC-492-package]
  workflow_dispatch:
    
jobs:
  publish:
    name: Publish OSCAL Viewer Build to GitHub Packages
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete previous oscal-react-library version
        uses: actions/delete-package-versions@v1
        with:
          package-name: oscal-react-library
      - name: Delete previous oscal-viewer version
        uses: actions/delete-package-versions@v1
        with:
          package-name: oscal-viewer
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          cache: npm
      - name: Update Npm
        run: npm install -g npm@latest
      - name: Build and Publish Library
        run:
          npm ci && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build and Publish OSCAL Viewer
        run:
          cd example && npm ci && npm run build && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

