---
name: Publish to GitHub Packages
on:
  push:
    branches: [develop]
  workflow_dispatch:

concurrency: package-push

jobs:
  publish:
    name: Publish OSCAL Viewer Build to GitHub Packages
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete previous oscal-react-library version
        uses: actions/delete-package-versions@v2.0.1
        with:
          package-name: oscal-react-library
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          cache: npm
      - name: Update Npm
        run: npm install -g npm@latest
      - name: Build and Publish Library
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
