name: Publish to GitHub Packages
on:
  push:
    branches: [EGRC-492-version]
  workflow_dispatch:

jobs:
  update_version:
    name: Update oscal-react-library and oscal-viewer version
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-20.04
    if: ${{ !endsWith(github.event.head_commit.message, 'Release') }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Update version of oscal-react-library packages
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.event.pusher.name }}"
          npm version patch -m "OSCAL React Library Release"
      - name: Update version of oscal-viewer package
        working-directory: ./example
        run: |
          npm version patch
      - name: Push changes to the repository
        run: |
          git add package.json
          git add package-lock.json
          git add example/package.json
          git add example/package-lock.json
          git commit -m "OSCAL Viewer Release"
          git push origin EGRC-492-version
  publish:
    name: Publish OSCAL Viewer Build to GitHub Packages
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    if: ${{ endsWith(github.event.head_commit.message, 'Release') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          cache: npm
      - name: Update Npm
        run: npm install -g npm@latest
      - name: Build and Publish Library
        run:
          npm ci && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build and Publish OSCAL Viewer
        run:
          cd example && npm ci && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}