name: Create a New Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number of this release'
        required: true

jobs:
  release:
    name: Create a New Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          cache: npm

      - name: Update Npm
        run: npm install -g npm@latest

      # Set package to the specified version
      # Store version as an environment variable for later steps to use.
      - name: Set Version of this Release
        run: |
          npm version ${{ github.event.inputs.version }}
          cd example
          npm version ${{ github.event.inputs.version }}

      - name: Build OSCAL Viewer
        working-directory: example
        run: |
          npm ci
          npm run build
          zip viewer.zip build

      - name: Create a GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name:
            ${{ github.event.inputs.version }}
          files:
            example/viewer.zip

      # Commit the new version and push changes to main, as well as a "tag-{version}" branch
      - name: Push to Main and Tag Branch
        run: |
          git add package.json package-lock.json example/package.json example/package-lock.json
          git commit -m "Create Release Version ${{ github.event.inputs.version }}"
          git push origin main
          git push -u origin tag-${{ github.event.inputs.version }}